Guru Yogeshwar-Flask-Assessment/app/__init__.py
from flask import Flask
from app.routes import main_routes
from app.product_routes import product_routes

def create_app():
    app = Flask(__name__)
    app.register_blueprint(main_routes)
    app.register_blueprint(product_routes)
    return app

Guru Yogeshwar-Flask-Assessment/app/routes.py
from flask import Blueprint, render_template

main_routes = Blueprint('main_routes', __name__)

# This is the route that will be displayed when the user visits the root URL of the site.


@main_routes.route('/')
def home():
    return render_template('home.html', title='Home', message='This is the home page.')


@main_routes.route('/about')
def about():
    return render_template('about.html', title='About', message='This is the about page.')

Guru Yogeshwar-Flask-Assessment/app/templates/about.html
about.html

{% extends "base.html" %}

{% block title %}{{title}}{% endblock %}

{% block content %}
<h1>{{title}}</h1>
<p>{{message}}</p>
<p>Welcome to the about page</p>
{% endblock %}

Guru Yogeshwar-Flask-Assessment/app/templates/base.html
base.html

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>

    <header>
        <nav>
            <ul>
                <li><a href="{{ url_for('main_routes.home')}}">Home</a></li>
                <li><a href="{{ url_for('main_routes.about') }}">About</a></li>
                <li><a href="{{ url_for('product_routes.index') }}">products</a></li>
                <!-- <li><a href="{{ url_for('product_routes.create') }}"> create products</a></li> -->
            </ul>
        </nav>
    </header>

    <main>
        {% block content %}
        {% endblock %}
    </main>

    <footer>
        <p>&copy; 2020 My Flask Project</p>
    </footer>

</body>

</html>

Guru Yogeshwar-Flask-Assessment/app/templates/home.html
home.html

{% extends "base.html" %}

{% block title %}{{title}}{% endblock %}

{% block content %}
<h1>{{title}}</h1>
<p>{{message}}</p>
<p>Welcome to the home page</p>
{% endblock %}

Guru Yogeshwar-Flask-Assessment/app/templates/products/create.html
{% extends "base.html" %}

{% block title %}
    Create Product
{% endblock %}

{% block content %}
    <h2>Creating a New Product</h2>
    <form method="post" action="{{ url_for('product_routes.create') }}">
      <label for="id">ID:</label>
      <input type="number" id="id" name="id" required>

      
        <label for="name">Name:</label>
        <input type="text" id="name" name="name" required>

        <label for="price">Price:</label>
        <input type="number" id="price" name="price" required>

        <button type="submit">Create Product</button>
    </form>
{% endblock %}

Guru Yogeshwar-Flask-Assessment/app/templates/products/index.html
{% extends "base.html" %}

{% block title %}Products Page{% endblock %}

{% block content %}
    <h3>Product List</h3>
    <ul>
        {% for product in products %}
            <li>
                {{ product.id }} - {{ product.name }} - ${{ product.price }}
                <a href="{{ url_for('product_routes.update', product_id=product.id) }}">Update</a>
            </li>
        {% endfor %}
    </ul>
{% endblock %}

Guru Yogeshwar-Flask-Assessment/app/templates/products/update.html
{% extends "base.html" %}

{% block title %}Update Product{% endblock %}

{% block content %}
    <h2>Updating an Existing Product</h2>
    <form method="post" action="{{ url_for('product_routes.update', product_id=product_id) }}">
        <label for="id">ID:</label>
        <input type="number" id="id" name="id" value="{{ product.id }}" required>
        <br>
        
        <label for="name">Name:</label>
        <input type="text" id="name" name="name" value="{{ product.name }}" required>
        <br>
        
        <label for="price">Price:</label>
        <input type="number" id="price" name="price" value="{{ product.price }}" required>
        <br>
        
        <button type="submit">Update Product</button>
    </form>
{% endblock %}